from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP-2
    Generated by: David Stiven leon (ldavidz1999@gmail.com)
    Generated on 04/12/2021, 07:05:27
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="PSc4r5iDlXSHMibj4jOOkVAqcnPHQniWynK3ymF4xf8",
                              project_name="My first Project",
                              job_name="CP-2")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Inicio de sesion."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://example.testproject.io/web/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Navigate to 'https://idiv-cloud.webcindario.com/'
    driver.get("https://idiv-cloud.webcindario.com/")

    # 3. Click 'Iniciar Sesion1'
    iniciar_sesion1 = driver.find_element(By.XPATH,
                                          "//span[. = 'Iniciar Sesion']")
    iniciar_sesion1.click()

    # 4. Click 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.click()

    # 5. Type 'prc1' in 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.send_keys("prc1")

    # 6. Type '123456789' in 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.send_keys("123456789")

    # 7. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//i/input")
    input.click()
